name: built_redux_rx
version: 0.1.1
description:
   epics for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_rx
dependencies:
  built_redux: ">=6.1.1 <8.0.0"
  built_value: ^5.4.3
  rxdart: ^0.16.0

dev_dependencies:
  build_runner: ^0.8.3
  built_value_generator: ^5.4.3
  test: ^0.12.35
